presets:
  link:
    default: # used for all links
      latency: 0ns
      throughput: 10Gbps
      ingress_buffer_size: 4096B
      egress_buffer_size: 4096B
  
packet-spraying:
  type: ecmp

depth: 3 # count of layers
num_switches_per_device: 2 # count of childs of each device
receivers_count: 1 # must be >= 1